#This is a simple calculator i make using python
a = int(input("Enter First Number :"))
b = int(input("Enter Second Number :"))
print("Addition of", a, "and", b, "is :", a + b)
print("Subtraction of", a, "and", b, "is :", a - b)
print("Multiplication of", a, "and", b, "is :", a * b)
print("Division of", a, "and", b, "is :", a / b)
print("Modulus of", a, "and", b, "is :", a % b)
print("floor Division of", a, "and", b, "is :", a // b)
print("Exponential of", a, "and", b, "is :", a ** b)